import turtle

turtleDrawer = turtle.Turtle()
turtleDrawer.getscreen().bgcolor("black")
turtleDrawer.color("black")
turtleDrawer.shape("turtle")
turtleDrawer.goto(-200,0)
turtleDrawer.speed(0)

#M
turtleDrawer.penup()
turtleDrawer.right(180)
turtleDrawer.forward(175)
turtleDrawer.right(90)
turtleDrawer.color("green")
turtleDrawer.begin_fill()
turtleDrawer.pendown()
turtleDrawer.forward(50)
turtleDrawer.right(140)
turtleDrawer.forward(25)
turtleDrawer.left(100)
turtleDrawer.forward(25)
turtleDrawer.right(140)
turtleDrawer.forward(50)
turtleDrawer.left(90)
turtleDrawer.forward(10)
turtleDrawer.left(90)
turtleDrawer.forward(70)
turtleDrawer.left(135)
turtleDrawer.forward(35)
turtleDrawer.right(90)
turtleDrawer.forward(35)
turtleDrawer.left(135)
turtleDrawer.forward(70)
turtleDrawer.left(90)
turtleDrawer.forward(10)
turtleDrawer.end_fill()

#A
turtleDrawer.penup()
turtleDrawer.forward(50)
turtleDrawer.left(65)
turtleDrawer.begin_fill() 
turtleDrawer.pendown()
turtleDrawer.color("blue")
turtleDrawer.forward(70)
turtleDrawer.right(125)
turtleDrawer.forward(70)
turtleDrawer.right(119)
turtleDrawer.forward(63)
turtleDrawer.end_fill()

#T 1
turtleDrawer.penup()
turtleDrawer.right(180)
turtleDrawer.forward(95)
turtleDrawer.pendown()
turtleDrawer.color("white")
turtleDrawer.begin_fill()
turtleDrawer.left(90)
turtleDrawer.forward(50)
turtleDrawer.left(90)
turtleDrawer.forward(20)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.right(90)
turtleDrawer.forward(60)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.left(90)
turtleDrawer.forward(50)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.end_fill()

#T 2
turtleDrawer.right(180)
turtleDrawer.penup()
turtleDrawer.forward(80)
turtleDrawer.left(90)
turtleDrawer.pendown()
turtleDrawer.color("red")
turtleDrawer.begin_fill()
turtleDrawer.forward(50)
turtleDrawer.left(90)
turtleDrawer.forward(20)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.right(90)
turtleDrawer.forward(60)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.left(90)
turtleDrawer.forward(50)
turtleDrawer.right(90)
turtleDrawer.forward(20)
turtleDrawer.end_fill()

#H 
turtle.exitonclick()
turtleDrawer.right(180)
turtleDrawer.forward(50)