#import the turtle modules
import turtle

# Forming the window screen
tut = turtle.Screen()
pen = turtle.Turtle()
m = turtle.Turtle()
pen.penup()
pen.goto(-50,-50)
pen.pendown()
tut.bgcolor("tan")
pen.color("light green")
pen.begin_fill()
for i in range(4):
  pen.forward(100)
  pen.right(90)
pen.end_fill()
pen.begin_fill()
pen.left(45)
pen.forward(100)
pen.right(45)
pen.forward(100)
pen.right(135)
pen.forward(100)
pen.right(45)
pen.forward(100)
pen.end_fill()
pen.penup()
pen.right(180)
pen.forward(100)
pen.right(90)
pen.forward(100)
pen.left(90)
pen.pendown()
pen.begin_fill()
pen.left(45)
pen.forward(100)
pen.left(45)
pen.forward(100)
pen.left(135)
pen.forward(100)
pen.left(45)
pen.forward(100)
pen.end_fill()
pen.color("blue")
pen.hideturtle()
m.color("white")
m.penup()
m.goto(20,20)
m.pendown()
m.begin_fill()
for i in range(3):
  m.forward(100)
  m.left(120)
m.end_fill()