#import the turtle modules
import turtle

# Forming the window screen
tut = turtle.Screen()
pen = turtle.Turtle()
m = turtle.Turtle()
grass = turtle.Turtle() 
pen.penup()
pen.speed(0)
grass.speed(0)
m.speed(0)
pen.goto(-50,-50)
pen.pendown()
tut.bgcolor("light blue")
pen.color("light yellow")
pen.begin_fill()
for i in range(4):
  pen.forward(100)
  pen.right(90)
pen.end_fill()
pen.hideturtle()
m.color("yellow")
m.penup()
m.goto(-50,-50)
m.left(60)
m.pendown()
m.begin_fill()
m.forward(100)
m.right(120)
m.forward(100)
m.right(120)
m.forward(100)
m.end_fill()
m.hideturtle()
grass.penup()
grass.goto(0,-150)
grass.color("light green")
grass.backward(200)
grass.pendown()
grass.begin_fill()
for i in range(4):
  grass.forward(400)
  grass.right(90)
grass.end_fill()